### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by govann** [SuhailSaify/Justdial-Scrapper#2]

**Comment by govann** [comment]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vanshtaneja/jd/justDail_scraper.py", line 253, in get_data_from_url
    phone_no=(get_phone_no(wd.page_source))
  File "/Users/vanshtaneja/jd/justDail_scraper.py", line 20, in get_phone_no
    sheet = cssutils.parseString(str(style[len(style)-1].text))
AttributeError: module 'cssutils' has no attribute 'parseString'
`

**Comment by SuhailSaify** [comment]
Hi

Please try
`cmd/terminal>python>import cssutils`

and let me know if it throws an error.

This error occurs due to improper installation.
