### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by dhekabai** [SuhailSaify/Justdial-Scrapper#3]
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\Justdial-Scrapper-master\get.py", line 5, in <module>
    get_data_from_url(ex_url,print_response=True)
  File "C:\Users\XXX\Desktop\Justdial-Scrapper-master\justDail_scraper.py", line 253, in get_data_from_url
    phone_no=(get_phone_no(wd.page_source))
  File "C:\Users\XXX\Desktop\Justdial-Scrapper-master\justDail_scraper.py", line 20, in get_phone_no
    sheet = cssutils.parseString(str(style[len(style)-1].text))
IndexError: list index out of range

I have a get.py file with just the example code:

```
from justDail_scraper import get_data_from_url

ex_url='https://www.justdial.com/Delhi/Dr-S-K-Mundhra-Opposite-St-Margreet-School-Prashant-Vihar/011PXX11-XX11-130130123521-H6P2_BZDET?xid=RGVsaGkgQ2xpbmljcw=='

get_data_from_url(ex_url,print_response=True)
```

**Comment by dhekabai** [comment]
`from justDail_scraper import get_data_from_url

ex_url='https://www.justdial.com/Delhi/Dr-S-K-Mundhra-Opposite-St-Margreet-School-Prashant-Vihar/011PXX11-XX11-130130123521-H6P2_BZDET?xid=RGVsaGkgQ2xpbmljcw=='

get_data_from_url(ex_url,print_response=True)`
